mgrachev/update-informer

- .github/workflows/ci.yml
- .github/workflows/linters.yml
- .github/workflows/release.yml
- CHANGELOG.md
- README.md
> Set up CI/CD

- CHANGELOG.md
- Cargo.toml
- README.md
- src/lib.rs
- src/package.rs
- src/registry.rs
- src/registry/crates.rs
- src/registry/github.rs
- src/test_helper.rs
- src/version.rs
- src/version_file.rs
> WIP: Save latest version to file and add interval check

- CHANGELOG.md
- README.md
- src/lib.rs
- src/registry.rs
- src/registry/crates.rs
- src/registry/github.rs
> docs: add documentation and update examples

- CHANGELOG.md
- Cargo.toml
- README.md
- src/lib.rs
- src/registry.rs
> Add `UpdateInformer` and `FakeUpdateInformer` structs for convenient use

- .github/actions-rs/grcov.yml
- .github/workflows/ci.yml
- CHANGELOG.md
- README.md
> Set up test coverage

- CHANGELOG.md
- examples/crates.rs
- examples/github.rs
- examples/pypi.rs
> chore: add more examples

- CHANGELOG.md
- README.md
- examples/crates.rs
- examples/github.rs
- examples/pypi.rs
- src/http.rs
- src/lib.rs
- src/registry.rs
- src/registry/crates.rs
- src/registry/github.rs
- src/registry/pypi.rs
> feat: add configurable request timeout and interval

- CHANGELOG.md
- Cargo.toml
- README.md
- examples/pypi.rs
- rust-toolchain.toml
- src/lib.rs
- src/package.rs
- src/registry.rs
- src/registry/crates.rs
- src/registry/github.rs
- src/registry/pypi.rs
- src/test_helper.rs
- src/version_file.rs
> A better cache directory naming scheme

- CHANGELOG.md
- Cargo.toml
- README.md
- src/http.rs
- src/lib.rs
- src/registry.rs
> feat: add cargo features

- .codecov.yml
- CHANGELOG.md
- Cargo.toml
- README.md
- examples/crates.rs
- examples/github.rs
- examples/pypi.rs
- src/lib.rs
- src/test_helper.rs
- src/version_file.rs
> feat: add ability to not use cache files

- .github/dependabot.yml
- CHANGELOG.md
> chore: add dependabot

- .github/workflows/stale.yml
- CHANGELOG.md
- Cargo.toml
> chore: add `stale` action

- .github/workflows/stale.yml
> chore: update `stale` action schedule

- .github/workflows/stale.yml
> chore: update `stale` schedule

- .github/workflows/ci.yml
- CHANGELOG.md
- Cargo.toml
- README.md
- examples/crates.rs
- examples/github.rs
- examples/pypi.rs
- rust-toolchain.toml
- src/http.rs
- src/lib.rs
- src/package.rs
- src/registry.rs
- src/registry/crates.rs
- src/registry/github.rs
- src/registry/pypi.rs
- src/test_helper.rs
- src/version.rs
- src/version_file.rs
> feat: add ability to implement your own registry

- .github/workflows/ci.yml
- .github/workflows/linters.yml
- CHANGELOG.md
- README.md
- src/lib.rs
> ci: add action to check links + ci optimization

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/ci.yml
- CHANGELOG.md
- Cargo.toml
- README.md
- dprint.json
- src/registry/pypi.rs
- tests/fixtures/registry/pypi/not_found.html
- tests/fixtures/registry/pypi/not_found.json
- tests/fixtures/registry/pypi/release.json
> ci: add `dprint` to check formatting

- .github/workflows/ci.yml
- CHANGELOG.md
- Cargo.toml
- README.md
- src/lib.rs
> ci: add cargo-sort

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/ci.yml
- .github/workflows/release.yml
- CHANGELOG.md
- Cargo.toml
- README.md
- cliff.toml
- release.sh
> chore: generate a changelog and update release process

- .github/workflows/release.yml
- CHANGELOG.md
- cliff.toml
- release.sh
> chore: get rid of `orhun/git-cliff-action`

- src/lib.rs
> refactor: remove deprecated function

- Cargo.toml
- README.md
- examples/npm.rs
- src/lib.rs
- src/registry.rs
- src/registry/crates.rs
- src/registry/npm.rs
- src/registry/pypi.rs
- src/test_helper.rs
- tests/fixtures/registry/npm/latest.json
- tests/fixtures/registry/npm/not_found.html
> feat: add `npm` registry support

- README.md
- src/lib.rs
- src/package.rs
- src/registry/crates.rs
- src/registry/github.rs
- src/registry/mod.rs
- src/registry/npm.rs
- src/registry/pypi.rs
- src/version.rs
- src/version_file.rs
> refactor!: move current_version to package

- README.md
- src/http_client/mod.rs
- src/http_client/reqwest.rs
- src/http_client/ureq.rs
- src/lib.rs
> feat: add ability to use your own http client

- .github/workflows/linters.yml
- src/package.rs
- src/registry/crates.rs
- src/registry/github.rs
- src/registry/pypi.rs
> ci: check PR name instead of commits

- src/lib.rs
> feat: add `http_client` method for  `FakeUpdateInformer`

- .github/workflows/ci.yml
- README.md
- src/http_client/mod.rs
- src/http_client/undefined.rs
- src/lib.rs
- src/package.rs
- src/registry/crates.rs
- src/registry/github.rs
- src/registry/mod.rs
- src/registry/npm.rs
- src/registry/pypi.rs
- src/version.rs
> feat: use undefined http client if no other is selected

- CHANGELOG.md
- Cargo.toml
- README.md
> chore(release): v1.0.0

- Cargo.toml
- README.md
> feat: add `rustls-tls`, `native-tls` features to enable equivalent features in `ureq` and `reqwest`

- README.md
> chore(docs): add `fselect` as user in README

- .github/workflows/ci.yml
> chore(ci): rollback codecov to v3

- Cargo.toml
- *Not applicable:* [ ] Tests for the changes have been added (for bug fixes / features).
Closes #142.
> chore: direct docs.rs via Cargo.toml to document all registries

- README.md
Thanks for maintaining such a nice crate!
I released a new version of fzf-make which can notify a new version.
If you don't mind, I would be happy to add fzf-make to users.
> chore(docs): add `fzf-make` as user in README

- .github/actions-rs/grcov.yml
- .github/workflows/ci.yml
- README.md
> chore(CI): fix CI and linter warnings

- CHANGELOG.md
- Cargo.toml
> chore(release): v1.2.0

- README.md
> chore(docs): add `nushell` as user in README

- CHANGELOG.md
- Cargo.toml
> chore(release): v1.3.0
